### ISSUE TITLE
_internal_create_key

### ISSUE THREAD

**Issue by shoaib3737** [CyberMaryVer/speech-emotion-webapp#1]
Dear 

When I try to execute   "api-test.py"  as per   README

I faced following error ,  Please help 

speech-emotion-webapp/api-test.py
Traceback (most recent call last):
  File "E:/2/ACL2020_Paper1_MOSEI_UMONS-master/MOSEI_UMONS-master/speech-emotion-webapp/api-test.py", line 5, in <module>
    import streamlit as st
  File "C:\Users\Shoaib\AppData\Local\Programs\Python\Python37\lib\site-packages\streamlit\__init__.py", line 49, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "C:\Users\Shoaib\AppData\Local\Programs\Python\Python37\lib\site-packages\streamlit\proto\RootContainer_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

Process finished with exit code 1

**Comment by CyberMaryVer** [comment]
Hi,

First of all, please use **app.py** to run the application

To resolve this issue you should probably upgrade pip
`pip install --upgrade protobuf`
or
`pip3 install --upgrade protobuf`

If this does not resolve the issue, please redeploy the application using the updated **requirements.txt** file.
